name: comment

on: 
  schedule:
    # Run every six hours
    - cron: '30 20,2,8,14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytz
        pip install dropbox

    - name: check and possibly refresh dropbox token
      run: |
        # Default to the stored secret token
        ACCESS_TOKEN=${{ secrets.DROPBOX_TOKEN }}

        # Check token validty
        TOKEN_VALIDITY=$(curl -X POST https://api.dropboxapi.com/2/users/get_current_account \
          --header "Authorization: Bearer $ACCESS_TOKEN" \
          --write-out "%{http_code}" --silent --output /dev/null)

        # If token is not valid, adjust as needed
        if [ "$TOKEN_VALIDITY" -ne 200 ]; then
            echo "Token is invalid or expired. Refreshing..."
            TOKEN_RESPONSE=$(curl -X POST https://api.dropboxapi.com/oauth2/token \
              -d grant_type=refresh_token \
              -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} \
              -u ${{ secrets.DROPBOX_APP_KEY }}:${{ secrets.DROPBOX_APP_SECRET }})

            # Extract the new access token
            ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')
        # otherwise, keep the default
        else
            echo "Token is still valid!"
        fi

        # Export the token to the env for subsequent steps
            echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

    - name: Run comment crawler
      run: |
        cd weibospider
        python run_spider.py comment
        
    - name: Rename and log
      run: |
        cd weibospider
        python comment_rename_and_log_output.py
