name: run keyword tracker every hour

on: 
  push:
    paths: '.github/workflows/keyword.yml'
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytz

    - name: Run my task
      run: |
        cd weibospider
        python run_spider.py tweet_by_keyword  

    - name: Dubug List Files
      run: |
        pwd && ls -l

    - name: Upload new output to Dropbox
      env: 
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        for file in output/*; do
          if [ -f "$file" ]; then
            FILENAME=$(basename $file)
            echo "Attempting to upload file: $FILENAME"
            curl -X POST https://content.dropboxapi.com/2/files/upload \
              --header "Authorization: Bearer $DROPBOX_TOKEN" \
              --header "Content-Type: application/octet-stream" \
              --header "Dropbox-API-Arg: {\"path\": \"/Dissertation/weibo_data/$FILENAME\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
              --data-binary @"$file"
          fi
        done
       
