name: run keyword tracker every hour

on: 
  push:
    paths: '.github/workflows/keyword.yml'
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytz

    - name: Run my task
      run: |
        cd weibospider
        python run_spider.py tweet_by_keyword  

    - name: Upload new output to Dropbox
      env: 
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        upload_endpoint="https://content.dropboxapi.com/2/files/upload"
        find . -type f -mmin -5 | while IFS= read -r file; do
          if [[ -r "$file" ]]; then  # Check if the file is readable
            echo "Uploading $file to Dropbox..."
            curl -X POST $upload_endpoint \
              --header "Authorization: Bearer $DROPBOX_TOKEN" \
              --header "Dropbox-API-Arg: {\"path\": \"/Dissertation/weibo_data/$(basename \"$file\")\",\"mode\": \"add\",\"autorename\": true,\"mute\": false,\"strict_conflict\": false}" \
              --header "Content-Type: application/octet-stream" \
              --data-binary @"$file"
          else
            echo "Cannot read $file. Skipping..."
          fi
        done
