name: run keyword tracker every hour

on: 
  push:  
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytz

    - name: check and possibly refresh dropbox token
      run: |
        TOKEN_VALIDITY=$(curl -X POST https://api.dropboxapi.com/2/users/get_current_account \
          --header "Authorization: Bearer ${{ secrets.DROPBOX_TOKEN }}" \
          --write-out "%{http_code}" --silent --output /dev/null)
          
        if [ "$TOKEN_VALIDITY" -ne 200 ]; then
            echo "Token is invalid or expired. Refreshing..."
            TOKEN_RESPONSE=$(curl -X POST https://api.dropboxapi.com/oauth2/token \
              -d grant_type=refresh_token \
              -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} \
              -u ${{ secrets.DROPBOX_APP_KEY }}:${{ secrets.DROPBOX_APP_SECRET }})
              
            export ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')
            echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
            # Optionally update the DROPBOX_REFRESH_TOKEN secret here if Dropbox provides a new refresh token.
            # NEW_REFRESH_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.refresh_token')
        else
            echo "Token is still valid!" >> $GITHUB_ENV
        fi

    - name: Run my task
      run: |
        cd weibospider
        python run_spider.py tweet_by_keyword  

    - name: Dubug List Files
      run: |
        pwd && ls -l

    - name: Upload new output to Dropbox
      env: 
        DROPBOX_TOKEN: $ACCESS_TOKEN
      run: |
        for file in output/*; do
          if [ -f "$file" ]; then
            FILENAME=$(basename $file)
            echo "Attempting to upload file: $FILENAME"
            curl -X POST https://content.dropboxapi.com/2/files/upload \
              --header "Authorization: Bearer $DROPBOX_TOKEN" \
              --header "Content-Type: application/octet-stream" \
              --header "Dropbox-API-Arg: {\"path\": \"/Dissertation/weibo_data/$FILENAME\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
              --data-binary @"$file"
          fi
        done
       
