name: run keyword tracker every three hours

on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6'

    - name: install python packages
      run: |
        cd WeiboSpider
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run my task
      run: |
        cd weibospider
        python run_spider.py tweet_by_keyword  
