name: test

on: 
  push:
    paths: '.github/workflows/test.yml'
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytz

    - name: Run my task
      run: |
        cd weibospider
        python run_spider.py follow

    - name: Dubug List Files
      run: |
        ls -R
        find . -name "*.jsonl"

    - name: Debug add permissions to the file
      run: |
        chmod +r $FILENAME

    - name: Debug Verify file content
      run: |
        ls -lh $FILENAME
        cat $FILENAME

    - name: Debug Print current directory and its contents
      run: | 
        pwd && ls -l 
      
    - name: Upload new output to Dropbox
      env: 
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        export FILENAME=$(basename $(find . -name "*.jsonl" -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" "))
        echo "Attempting to upload file: $FILENAME"
        curl -X POST https://content.dropboxapi.com/2/files/upload \
          --header "Authorization: Bearer $DROPBOX_TOKEN" \
          --header "Content-Type: application/octet-stream" \
          --header "Dropbox-API-Arg: {\"path\": \"/Dissertation/weibo_data/$FILENAME\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
          --data-binary @"$FILENAME"

